title: Shiran Tips
description: The long awaited blog on data analysis in Hebrew

url: shiran.tips
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, jekyll-gist]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Talks
    url: /talks

social:
  linkedin: shiran-krasnov
  email: krasnov.shiran@gmail.com

google_analytics: "UA-143777184-1"
