title: Shiran Tips
description: "I :heart: Data"

url: shiran.tips
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, jekyll-gist, jemoji]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Talks
    url: /talks
  - title: Data Interview
    url: /interviews


collections:
  interviews:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "interviews"
    values:
      layout: "interview"

social:
  linkedin: shiran-krasnov
  email: krasnov.shiran@gmail.com

google_analytics: "UA-143777184-1"
