version: "3.2"
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - type: bind
        source: ../vendor/bundle
        target: /usr/local/bundle
      - type: bind
        source: ..
        target: /srv/jekyll
    working_dir: /srv/jekyll
    ports:
      - "4000:4000"
    command: jekyll serve --watch
